/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    gallery: Gallery;
    orders: Order;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * محصولاتی که در سایت نمایش داده می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * خودکار از روی نام محصول ساخته می‌شود. اگر لازم بود می‌توانید تغییرش دهید.
   */
  slug?: string | null;
  category:
    | 'birthday-cakes'
    | 'cafe-cakes'
    | 'cookies'
    | 'dry-pastries'
    | 'desserts'
    | 'healthy'
    | 'diet-cookies'
    | 'spreads'
    | 'gift-packs'
    | 'sport-drinks';
  /**
   * یک عکس واضح از خود محصول. بدون عکس، محصول در سایت جذاب دیده نمی‌شود.
   */
  image: number | Media;
  /**
   * یک یا دو جمله درباره طعم و مواد اولیه. حداکثر ۲۰۰ حرف.
   */
  description?: string | null;
  /**
   * اگر تیک بخورد، به‌جای قیمت عبارت «استعلام قیمت» نمایش داده می‌شود.
   */
  priceOnRequest?: boolean | null;
  /**
   * فقط عدد، بدون نقطه یا ویرگول.
   */
  price?: number | null;
  /**
   * اگر تیک را بردارید، در سایت «فعلاً موجود نیست» نمایش داده می‌شود.
   */
  isAvailable?: boolean | null;
  /**
   * محصولات انتخاب‌شده در بخش «محصولات منتخب» صفحه اصلی نمایش داده می‌شوند.
   */
  isFeatured?: boolean | null;
  /**
   * عدد کوچک‌تر بالاتر نمایش داده می‌شود.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * آپلود و مدیریت تصاویر سایت.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * همان چیزی که در عکس است را بنویسید. مثال: کیک شکلاتی با توت‌فرنگی
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * عکس‌های نمونه کار که در بخش «نمونه کارها» سایت نمایش داده می‌شوند. برای حذف یک عکس از سایت، از همین لیست «حذف» بزنید — نه از دکمه حذف روی خود عکس.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * برای عوض کردن عکس، عکس جدید انتخاب کنید. برای حذف از سایت، کل این «نمونه کار» را از لیست نمونه کارها حذف کنید.
   */
  image: number | Media;
  /**
   * دکمه‌های فیلتر بالای گالری از روی همین دسته‌بندی ساخته می‌شوند. دسته‌ای که عکسی نداشته باشد در سایت نمایش داده نمی‌شود.
   */
  category:
    | 'birthday-cakes'
    | 'cafe-cakes'
    | 'cookies'
    | 'dry-pastries'
    | 'desserts'
    | 'healthy'
    | 'diet-cookies'
    | 'spreads'
    | 'gift-packs'
    | 'sport-drinks';
  /**
   * اختیاری. زیر عکس نمایش داده می‌شود.
   */
  caption?: string | null;
  /**
   * عدد کوچک‌تر جلوتر نمایش داده می‌شود.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * سفارش‌هایی که مشتری‌ها از طریق فرم سایت ثبت کرده‌اند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * تنها فیلدی که شما تغییر می‌دهید.
   */
  status: 'new' | 'confirmed' | 'delivered' | 'cancelled';
  customerName: string;
  phone: string;
  /**
   * محصولاتی که مشتری از سبد ثبت کرده است، با تعداد هر کدام.
   */
  items?:
    | {
        product: number | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * اگر مشتری «سایر» را هم نوشته باشد، اینجا می‌آید.
   */
  productNote?: string | null;
  /**
   * تعداد محصول متن آزاد.
   */
  otherQuantity?: number | null;
  deliveryDate?: string | null;
  notes?: string | null;
  /**
   * عکسی که مشتری به‌عنوان نمونه فرستاده است.
   */
  sampleImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * کاربران واردشونده به پنل مدیریت سایت.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * نامی که در پنل مدیریت برای شناسایی کاربر نمایش داده می شود.
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  image?: T;
  description?: T;
  priceOnRequest?: T;
  price?: T;
  isAvailable?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  category?: T;
  caption?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  customerName?: T;
  phone?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  productNote?: T;
  otherQuantity?: T;
  deliveryDate?: T;
  notes?: T;
  sampleImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * نام برند، عکس صفحه اول و اطلاعات تماس. این‌ها در کل سایت استفاده می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    brandName: string;
    /**
     * یک جمله کوتاه، مثال: طعم خانگی، با عشق و کیفیت
     */
    tagline?: string | null;
    /**
     * مثال: این هفته می‌پزیم
     */
    rotatingPrefix?: string | null;
    /**
     * زیر شعار برند، این کلمه‌ها یکی‌یکی تایپ و پاک می‌شوند. مثال: کیک تولد، شیرینی خشک، دسر. دست‌کم دو کلمه بگذارید تا بچرخند.
     */
    rotatingWords?:
      | {
          word: string;
          id?: string | null;
        }[]
      | null;
    /**
     * بزرگ‌ترین عکس سایت. بهترین عکس محصولتان را اینجا بگذارید.
     */
    heroImage: number | Media;
    /**
     * یک یا دو پاراگراف درباره خودتان و آشپزخانه. Enter برای پاراگراف جدید.
     */
    aboutText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * عکسی از آشپزخانه یا خودتان در حال کار.
     */
    aboutImage?: (number | null) | Media;
  };
  contact?: {
    phone?: string | null;
    /**
     * با کد کشور و بدون صفر و علامت، مثال: 989121234567
     */
    whatsapp?: string | null;
    /**
     * بدون علامت @، مثال: ghanad_bashi_asal5
     */
    instagram?: string | null;
    /**
     * مثال: اصفهان، بهارستان و حومه
     */
    serviceArea?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        brandName?: T;
        tagline?: T;
        rotatingPrefix?: T;
        rotatingWords?:
          | T
          | {
              word?: T;
              id?: T;
            };
        heroImage?: T;
        aboutText?: T;
        aboutImage?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        instagram?: T;
        serviceArea?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}